branch-defaults:
  initial-setup:
    environment: null
    group_suffix: null
deploy:
  artifact: com-worldpay-gateway-v4pp-paymentpages-1.16.0-SNAPSHOT.war
global:
  application_name: ec2SimpleTest
  branch: null
  default_ec2_keyname: NGPP
  default_platform: Tomcat 7 Java 7
  default_region: eu-west-1
  profile: eb-cli
  repository: null
  sc: git
